<a href="https://colab.research.google.com/github/SauravKumar710/Customer-Lifetime-Value-Predictor/blob/main/logregr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import linear_model
from sklearn.metrics import confusion_matrix
from sklearn import metrics

# Importing the dataset
dataset = pd.read_excel(r'/content/Dataset.xlsx')
dataset.head()

Customer_no  Age  Bank_Balance  (Average)Interest Rate Margin(%)  \
0            1   41      15139.00                              1.81   
1            2   41      54341.00                              1.61   
2            3   21      40554.80                              2.65   
3            4   37      59998.73                              2.37   
4            5   18      75661.51                              2.21   

   Loan_Interest  Fees_Service  Total_Earning  Retain_Amount  Service_Spent  \
0        4547.73       5000.00       24689.46         352.08         188.51   
1        4770.36       1864.29       60977.28         217.14         235.47   
2         615.75       3670.18       44843.38         198.23         116.00   
3        1549.40       3717.14       65267.64         111.43         169.16   
4        1732.38       3344.89       80740.99         467.49         132.71   

   Discount_Rate  Discount_Amount  Totl_Spend  Gross_Margin  Retention_rate  \
0            0.1           507.36     1048.05      23641.41           0.478   
1            0.1          1005.89     1458.60      59518.68           0.478   
2            0.1           987.73     1302.06      43541.32           0.478   
3            0.1          1643.14     1923.83      63343.81           0.478   
4            0.1          1434.05     2034.35      78706.64           0.478   

        CLV CLV_TYPE  
0  18168.16        L  
1  45739.44        M  
2  33461.01        M  
3  48679.01        M  
4  60485.17        M

In [3]:
a1={'L': 0,'M': 1,'H':2}
dataset['CLV_TYPE'] = dataset['CLV_TYPE'].map(a1)


In [4]:
# Our Independent Variables
X = dataset[['Bank_Balance','(Average)Interest Rate Margin(%)','Loan_Interest','Fees_Service','Total_Earning','Retain_Amount','Service_Spent','Discount_Rate','Discount_Amount','Gross_Margin','Retention_rate']]

# Our Dependent Variable Data frame
Y = dataset[['CLV_TYPE']] 
dataset.head()

Customer_no  Age  Bank_Balance  (Average)Interest Rate Margin(%)  \
0            1   41      15139.00                              1.81   
1            2   41      54341.00                              1.61   
2            3   21      40554.80                              2.65   
3            4   37      59998.73                              2.37   
4            5   18      75661.51                              2.21   

   Loan_Interest  Fees_Service  Total_Earning  Retain_Amount  Service_Spent  \
0        4547.73       5000.00       24689.46         352.08         188.51   
1        4770.36       1864.29       60977.28         217.14         235.47   
2         615.75       3670.18       44843.38         198.23         116.00   
3        1549.40       3717.14       65267.64         111.43         169.16   
4        1732.38       3344.89       80740.99         467.49         132.71   

   Discount_Rate  Discount_Amount  Totl_Spend  Gross_Margin  Retention_rate  \
0            0.1           507.36     1048.05      23641.41           0.478   
1            0.1          1005.89     1458.60      59518.68           0.478   
2            0.1           987.73     1302.06      43541.32           0.478   
3            0.1          1643.14     1923.83      63343.81           0.478   
4            0.1          1434.05     2034.35      78706.64           0.478   

        CLV  CLV_TYPE  
0  18168.16         0  
1  45739.44         1  
2  33461.01         1  
3  48679.01         1  
4  60485.17         1

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20 ,random_state = 0)


In [6]:
classifier = linear_model.LogisticRegression()
m=classifier.fit(X_train, Y_train)


/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [7]:
y_pred = classifier.predict(X_test)
print(y_pred)

[1 0 0 0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 1 0 0
 1 1 1 0 0 1 1 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 0 1 1 0 0 1 0 1 1 1 0 1 1 1
 1 1 1 1 1 1 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0 1 1 1 1 0 0 1 0 1
 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1 1 1 0 0
 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 0 1 1 0 0 0 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1]


In [8]:
cm = confusion_matrix(Y_test, y_pred)
print(cm)


[[ 65   4   0]
 [  5 123   0]
 [  1   2   0]]


In [9]:
print("Accuracy of Logistic Regression Model is:",
     metrics.accuracy_score(Y_test,y_pred)*100,"%")
X.head(5)

Accuracy of Logistic Regression Model is: 94.0 %


Bank_Balance  (Average)Interest Rate Margin(%)  Loan_Interest  \
0      15139.00                              1.81        4547.73   
1      54341.00                              1.61        4770.36   
2      40554.80                              2.65         615.75   
3      59998.73                              2.37        1549.40   
4      75661.51                              2.21        1732.38   

   Fees_Service  Total_Earning  Retain_Amount  Service_Spent  Discount_Rate  \
0       5000.00       24689.46         352.08         188.51            0.1   
1       1864.29       60977.28         217.14         235.47            0.1   
2       3670.18       44843.38         198.23         116.00            0.1   
3       3717.14       65267.64         111.43         169.16            0.1   
4       3344.89       80740.99         467.49         132.71            0.1   

   Discount_Amount  Gross_Margin  Retention_rate  
0           507.36      23641.41           0.478  
1          1005.89      59518.68           0.478  
2           987.73      43541.32           0.478  
3          1643.14      63343.81           0.478  
4          1434.05      78706.64           0.478

In [10]:
a=float(input("Enter The Customer Bank Balance:"))
b=float(input("Enter The (Average)Interest Rate Margin(%) :"))
c=float(input("Loan_Interest :"))
d=float(input("Fees_Service :"))
e=a+b+c+d
f=float(input("Retain_Amount :"))
g=float(input("Service_Spent :"))
h=float(input("Discount_Rate :"))
i=float(input("Discount_Amount :"))
j=e-f-g-h-i
k=float(input("Retention_rate :"))
print("The Predicted Value of CLV is :",classifier.predict([[a,b,c,d,e,f,g,h,i,j,k]]))
f=m.predict([[a,b,c,d,e,f,g,h,i,j,k]])
if f==0:
  print("The CLV is Low")
elif f==1:
  print("The CLV is Medium")
else:
  print("The CLV is High")

Enter The Customer Bank Balance:104900
Enter The (Average)Interest Rate Margin(%) :10.2
Loan_Interest :12000
Fees_Service :22000
Retain_Amount :500
Service_Spent :200
Discount_Rate :10
Discount_Amount :500
Retention_rate :0.562
The Predicted Value of CLV is : [1]
The CLV is Medium


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
